name: Revenant build pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Installing modules
        run: yarn
      - name: Building
        run: yarn build
      - name: Uploading pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./static
          name: github-pages
          retention-days: 1
          
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.0

  binaries:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
         node-version: "18.x"
      - name: Add wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo apt install software-properties-common
          sudo apt-add-repository 'deb http://dl.winehq.org/wine-builds/ubuntu/ bionic main'
          wget -qO- https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/Release.key | sudo apt-key add -
          sudo sh -c 'echo "deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/ ./" > /etc/apt/sources.list.d/obs.list'
          sudo apt update
          sudo apt-get install --install-recommends winehq-stable
      - name: Installing modules
        run: yarn
      - name: Building binaries
        run: yarn electron-build
      - name: Zip windows
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r win.zip dist/win-unpacked
      - name: Zip linux
        uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r linux.zip dist/linux-unpacked
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          files: |
            linux.zip
            win.zip
