name: Revenant build pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Installing modules
      - run: yarn
      - name: Building
      - run: yarn build
      - name: Uploading pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./static
          name: github-pages
          retention-days: 1
      - name: Deploy GitHub Pages
        uses: actions/deploy-pages@v2.0.0
