name: Revenant
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Run Yarn 
      run: yarn
    - name: Run build
      run: yarn build
    - name: unignore
      uses: JesseTG/rm@v1.0.0
      with:
        path: .gitignore
    - name: Add & Commit
      uses: EndBug/add-and-commit@v9.1.1
      with:
        push: origin master:deploy
