name: Revenant build pages
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
      - name: Installing modules
        run: yarn
      - name: Building
        run: yarn build
      - name: Uploading pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./static
          name: github-pages
          retention-days: 1
          
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.0

  binaries:
    runs-on: ubuntu-latest
    container: electronuserland/builder:wine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
         node-version: "18.x"
      - name: Installing modules
        run: yarn
      - name: Build/release Electron app
        uses: Yan-Jobs/action-electron-builder@v1.7.0
        with:
          build_script_name: no-maps
          github_token: ${{ secrets.github_token }}
          release: true
